# Makefile

build:
	poetry build

publish:
	poetry publish --dry-run

install:
	poetry install

package-install:
	python3 -m pip install --user /Users/dmitrykholopov/HEXLET/python-project-lvl1/dist/hexlet_code-0.1.0-py3-none-any.whl

lint:
	poetry run flake8 /Users/dmitrykholopov/HEXLET/python-project-lvl1/brain_games

brain-games:
	poetry run brain-games
